// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmY2lfnls8ksq5pzLoJpQdhoU9dn7rG2s',
    appId: '1:7708603750:android:134240a5a2e730ec07c4a7',
    messagingSenderId: '7708603750',
    projectId: 'wwnapp-e8f99',
    storageBucket: 'wwnapp-e8f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LCzWQ76hNDsjcELtFh8sRFoFXw9wPpE',
    appId: '1:7708603750:ios:51c5c3e63945378707c4a7',
    messagingSenderId: '7708603750',
    projectId: 'wwnapp-e8f99',
    storageBucket: 'wwnapp-e8f99.firebasestorage.app',
    iosClientId: '7708603750-npmp7bslhibb1132pdoh8eicqjilj42n.apps.googleusercontent.com',
    iosBundleId: 'com.example.wwnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LCzWQ76hNDsjcELtFh8sRFoFXw9wPpE',
    appId: '1:7708603750:ios:51c5c3e63945378707c4a7',
    messagingSenderId: '7708603750',
    projectId: 'wwnapp-e8f99',
    storageBucket: 'wwnapp-e8f99.firebasestorage.app',
    iosClientId: '7708603750-npmp7bslhibb1132pdoh8eicqjilj42n.apps.googleusercontent.com',
    iosBundleId: 'com.example.wwnApp',
  );
}
